// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBlNdWpWml2PuFNGdsclbW3M0VypDDHQ6s',
    appId: '1:320317641150:web:23d2ea79b57c10e98fe9ef',
    messagingSenderId: '320317641150',
    projectId: 'fir-flutter-45a3a',
    authDomain: 'fir-flutter-45a3a.firebaseapp.com',
    storageBucket: 'fir-flutter-45a3a.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAixydsuxJX5J9FA0nfhjRXt1r07Jcf8Q8',
    appId: '1:320317641150:android:c2c2452b22dffbb48fe9ef',
    messagingSenderId: '320317641150',
    projectId: 'fir-flutter-45a3a',
    storageBucket: 'fir-flutter-45a3a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAAoKwImTAOPE0TfTvWKFbKceMoAxdD4q4',
    appId: '1:320317641150:ios:f8d7de0a52040f928fe9ef',
    messagingSenderId: '320317641150',
    projectId: 'fir-flutter-45a3a',
    storageBucket: 'fir-flutter-45a3a.appspot.com',
    iosBundleId: 'com.example.bytelearn',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAAoKwImTAOPE0TfTvWKFbKceMoAxdD4q4',
    appId: '1:320317641150:ios:c43492a1b92964178fe9ef',
    messagingSenderId: '320317641150',
    projectId: 'fir-flutter-45a3a',
    storageBucket: 'fir-flutter-45a3a.appspot.com',
    iosBundleId: 'com.example.bytelearn.RunnerTests',
  );
}
